/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projecteGradleJoelMalonda;
import org.apache.commons.math3.primes.Primes;
public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int num1 = 3;
        int num2 = 8;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.println("El driver funciona");
            if (Primes.isPrime(num1)) {
                System.out.println("El número " + num1 + " és primo");
            } else {
                System.out.println("El número " + num1 + " no és primo");
            }
            if (Primes.isPrime(num2)) {
                System.out.println("El número " + num2 + " és primo");
            } else {
                System.out.println("El número " + num2 + " no és primo");
            }
        } catch (ClassNotFoundException e) {
            System.out.println("Error en el driver de la BD");
            System.out.println("Error: " + e.getMessage());
        }
    }
}
